### PR TITLE
dep 0.5.0

### PR DESCRIPTION
**Pull request by dcormier**

### CODE REVIEW

**Comment by rlguarino** [comment]
Thanks for updating this @dcormier !

**Comment by rlguarino** [comment]
I've uploaded the package: https://chocolatey.org/packages/dep/0.5.0

**Comment by rlguarino** [comment]
@dcormier If you're interested I'll make you a maintainer of this project. Let me know and I can look into getting you access to push to chocolately.org or I can setup CI.

**Comment by dcormier** [comment]
I don't anticipate being _super_ active, but if the timing is right I certainly would update it if I had access.

**Pull request merged**
